# Site wide configuration

title: LoneReads
locale: en_US
description: A by-yourself online book club (BYOBC)
logo: lone-reads-logo.png
search: true
#url: http://localhost:4000 
url: http://lonereads.com 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: LoneReads
  avatar: lone-reads-logo.png
  email: lonereads@gmail.com
  disqus-shortname:
  twitter: lonereads
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #lonereads
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
